name: CI Pipeline
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runner context values
        run: |
          echo "Runner OS   : ${{ runner.os }}"
          echo "Runner arch : ${{ runner.arch }}"
