name: CI Pipeline
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build Successful"
      - name: Test
        if: ${{ success() }}
        run: echo "Testing Application"
