name: CI Pipeline
on: 
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        if: ${{ success() && github.event_name == 'workflow_dispatch' }}
        run: echo "Deploying to Production"
